name: Continuous integration
on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dbpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.4.2"
      - name: Install dependancies
        run: |
          poetry install
      - name: Lint
        run: |
          poetry run black --check .
          poetry run mypy .
          poetry run ruff check .
      - name: Test
        env:
          USE_EXISTING_PG: 1
        run: |
          poetry run pytest --postgresql-password=dbpassword
